# It is a workflow file for github actions
# all the steps performed in local, will now perform at GitHub Actions

name: Python application

# when push or pull is done on the main branch then only this action runs
# until then there wont be any kind of action happens

on:
  push: 
    branches:
    - main #(brach name)
  pull_request:
    branches:
    - main #(Branch name)
# once push or pull command is run then step by step all stages of jobs will run
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
 #       pip install flake8 pytest #(it is already in requirements.txt)
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi #bash coding syntax(starts
        # with "if", condition given and then end using "fi")
    #- name: Lint with flake8
    #  run: |
        # stop the build if there are Python syntax errors or undefined names
    #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest -v
 #   - name: Deploy to Heroku
 #     env:
 #       HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
 #       HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
 #     if: github.ref == 'refs/heads/main' && job.status == 'success'
 #     run: |
 #       git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git
 #       git push heroku HEAD:main -f